### ISSUE TITLE
The app cannot be found from the Nextcloud instance, but it's available on apps.nextcloud.com

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj-thirdparty/nextcloud-app#1]
The app cannot be found from the Nextcloud instance, but it's available on https://apps.nextcloud.com/?search=storj
So, forced to download it and extract to the `apps` folder in Nextcloud. What's the reason?
Nextcloud v22.1.1

**Comment by Erikvv** [comment]
I'm not sure why, I'll investigate.

**Comment by Erikvv** [comment]
Fixed, just seems some delay in combination that I marked 0.0.1 as a nightly release.
