### ISSUE TITLE
Nextcloud integration with storj as primary

### ISSUE THREAD

**Issue by pablocarreraest** [storj-thirdparty/nextcloud-app#18]
I'm trying to config Storj as primary with this specs mention below [nevertheless i'm not into php]:

- Architecture: x64
- Nextcloud version: 23.0.1
- PHP version: 8.0.16
- Using Storj as primary or external storage: primary

My problems are the follow:

1) Death link at main menu for the link of Storj [clicked and don't show nothing].

2) I config as you show in the README file but don't know if is working or anything. This is suppose to upload files on the bucket I assing to but nothing happens. Also should I comment **_datadirectory_**  on the config file or what should a do with this? sorry for the naive questions.

Do you have an example config for this to work or any guide to point me in the right direction?

**Comment by pablocarreraest** [comment]
I was right... miss understands why on the bucket don't show me the files. Sorry ;)

**Comment by Erikvv** [comment]
> Death link at main menu for the link of Storj [clicked and don't show nothing].

That is not meant to be there but it wouldn't let me publish the app without it. I will try again if this is now different than before. 

> what are the pros and cons of using as primary storage?

pro: your webserver is now stateless and does not use any storage other than SQL and Storj.

con: all of Nextcloud becomes a bit slower
con: all the small files like thumbnails will increase your Storj bill.

**Comment by pablocarreraest** [comment]
Hi @Erikvv, thanks for your amazing contribution and work.

Yes, I was worry because it become slower.. (I'm on a VM with 1 humble core and 1GB humble of ram).

What should be better VM specs for good performance if I use as a primary storage? I'm on a near region / satellite - server / bucket

> con: all of Nextcloud becomes a bit slower
> con: all the small caches like thumbnails will increase your Storj bill rather needlessly.

This cons you talk to me is with any other object storage that is use as a primary object with nextcloud?

For now this is for a small company so I setup to use as a external storage (I'm current on the free plan 150GB so no worries from Storj bill).

Just learning this two amazing solutions and thanks again for your response :)

**Comment by Erikvv** [comment]
> This cons you talk to me is with any other object storage that is use as a primary object with nextcloud?

Yeah basically.

> For now this is for a small company so I setup to use as a external storage (I'm current on the free plan 150GB so no worries from Storj bill).

This should be fine I've had no complaints about this.
