### ISSUE TITLE
Trying to open external storage - Storage is temporarily not available

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj-thirdparty/nextcloud-app#2]
Used docker version of Nextcloud. Because of #1 I downloaded archive and extracted it to the `apps` folder inside the container.
Installed external storage using this app and access grant from us2.storj.io

![image](https://user-images.githubusercontent.com/26858949/135336206-91b8f125-c070-4208-a75d-e8b88b183d17.png)

When I try to open a folder - I got an error:
```
Storage is temporarily not available
```
![image](https://user-images.githubusercontent.com/26858949/135336354-0571d814-9311-41f9-adeb-996153ca4d5a.png)
The bucket is exist:
```
uplink --access us2 ls
BKT 2021-08-22 16:59:55 duplicati
BKT 2021-09-21 11:58:26 nextcloud
BKT 2021-08-25 21:55:12 restic-test
```

**Comment by Erikvv** [comment]
Thank you for trying it out.

I've tested with Nextcloud 22 and uploaded a new release (0.0.2) to fix the probable issue.

If the problem persist you can click the :heavy_check_mark: in your screenshot and it will test the connection and it may display an error.

Else there should be an error in the logs (/data/nextcloud.log)

**Comment by Erikvv** [comment]
Can you tell me
- OS
- PHP version
- chip architecture
?

**Comment by sammosna** [comment]
I'm on Raspberry Pi 4 - so it's arm64 - with Ubuntu 20.04 and PHP 7.4.3.
Thank you, I'll be waiting for ARM support.

**Comment by Erikvv** [comment]
ARM support is done.
