### ISSUE TITLE
[PHP] Error: Module 'FFI' already loaded at Unknown#0

### ISSUE THREAD

**Issue by nunesgh** [storj-thirdparty/nextcloud-app#22]
Hi there,

I have just installed the app and enabled the PHP FFI extension as instructed, but now my Nextcloud instance logs are being flooded with the following error:
`[PHP] Error: Module 'FFI' already loaded at Unknown#0`

It seems to me that other apps also load the PHP FFI extension by themselves, which then causes the error.

My Nextcloud instance information:
- Architecture: x64
- Nextcloud version: 23.0.3
- PHP version: 7.4.28
- Storj app version: 0.0.7
- Using Storj as primary or external storage: external storage

Thank you for your attention.

**Comment by Erikvv** [comment]
This means you have `extension=ffi` twice in your config. 

Maybe it is once in `[/usr/local]/etc/php/php.ini` 
and then again in a file in `[/usr/local]/etc/php/conf.d/`

**Comment by nunesgh** [comment]
You are correct!

If I add `ffi.enable=true` to `/etc/php/php.ini` but leave the already existing `extension=ffi` line commented-out, the PHP error no longer appears.

Thank you for help!
