### ISSUE TITLE
Question regarding encryption design decision

### ISSUE THREAD

**Issue by nunesgh** [storj-thirdparty/nextcloud-app#23]
Hi,

This is not a bug, but actually a question regarding this app's encryption design.

According to Storj's documentation, there are two options: [End-to-end Encryption](https://docs.storj.io/dcs/concepts/encryption-key/design-decision-end-to-end-encryption/) and [Server-side Encryption](https://docs.storj.io/dcs/concepts/encryption-key/design-decision-server-side-encryption/).

Which one was used for this app? Would it be possible to use End-to-end Encryption, if this is not already the case?

Thank you for your attention.

**Comment by Erikvv** [comment]
From the perspective of Nextcloud/Storj it is end-to-end encryption. Your Nextcloud instance has your encryption key, but the Storj app does not send it to Storj. The app does not use the S3 gateway like described it your link. It connects directly to the storage nodes.

From the user/browser perspective it is not end-to-end encrypted because decryption takes place on the server, not on the users device. That's how Nextcloud currently works.

I hope this clears it up.

**Comment by nunesgh** [comment]
Hi @Erikvv,

Thank you for your thorough and quick response!

So this means that I should generate an Access Grant from Storj via the CLI, as instructed [here](https://docs.storj.io/dcs/api-reference/s3-compatible-gateway/#cli)?

Otherwise, as far as I understand, generating the Access Grant via Browser would automatically create a Server-side Encryption in the Storj perspective, i.e. the encryption would be performed outside my Nextcloud instance.

**Comment by Erikvv** [comment]
> So this means that I should generate an Access Grant from Storj via the CLI, as instructed [here](https://docs.storj.io/dcs/api-reference/s3-compatible-gateway/#cli)?
>
> Otherwise, as far as I understand, generating the Access Grant via Browser would automatically create a Server-side Encryption in the Storj perspective, i.e. the encryption would be performed outside my Nextcloud instance.

No this is not true. If you use uplink (and the nextcloud app uses uplink) it is always e2e encryption, even if you generated the access grant in the browser. We do not store your encryption key in this case.

But it's still a good habit to use uplink-cli.

**Comment by nunesgh** [comment]
Thank you so much for all the clarification and for your work on this app, @Erikvv!

All the best!
