### ISSUE TITLE
Error when adding files

### ISSUE THREAD

**Issue by declanmarks** [storj-thirdparty/nextcloud-app#24]
When I try and copy files to Storj external storage I get the following error

Sabre\DAV\Exception: uplink: stream: ecclient: successful puts (0) less than or equal to repair threshold (35) storj.io/uplink/private/ecclient.(*ecClient).put:186 storj.io/uplink/private/ecclient.(*ecClient).PutSingleResult:67 storj.io/uplink/private/storage/streams.(*Store).Put:249 storj.io/uplink/private/stream.NewUpload.func1:47 golang.org/x/sync/errgroup.(*Group).Go.func1:57

/var/www/html/apps/dav/lib/Connector/Sabre/File.php - line 289:
OCA\DAV\Connector\Sabre\File->convertToSabreException(Storj\Uplink ... {})
/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php - line 155:
OCA\DAV\Connector\Sabre\File->put(null)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1098:
OCA\DAV\Connector\Sabre\Directory->createFile("DSCF1004.JPG", null)
/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 504:
Sabre\DAV\Server->createFile("Photos/FUJI/DSCF1004.JPG", null, null)
/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:
Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 472:
Sabre\DAV\Server->emit("method:PUT", [ Sabre\HTTP ... }])
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 253:
Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 321:
Sabre\DAV\Server->start()
/var/www/html/apps/dav/appinfo/v1/webdav.php - line 83:
Sabre\DAV\Server->exec()
/var/www/html/remote.php - line 166:
require_once("/var/www/ht ... p")

- Architecture: x64
- Nextcloud version: 23.0.3
- PHP version: 
- Using Storj as primary or external storage: External

**Comment by Erikvv** [comment]
You might be exceeding the file handle limit: you can check it with `ulimit -n` with the webserver user, it might be 1024 which is too low quickly.

Probably you can increase it in the systemd service definition. 
For example for docker in `systemd/system/multi-user.target.wants/docker.service`:

```
[Service]
LimitNOFILE=1048576
```

Please let me know if this helped you. If this is the case I'll include it in the readme.

**Comment by declanmarks** [comment]
I ran echo exec('ulimit -n'); which returned, 1048576. Same as the file limit you provided.

**Comment by declanmarks** [comment]
I'm guessing it is a firewall issued. I do have a pfsense firewall with locked down ports.

I have attached a screenshot of the logs when doing a uplink cp command.

![Screenshot from 2022-04-23 13-22-22](https://user-images.githubusercontent.com/9248192/164894333-233eb741-f79e-4716-a5a9-6ca05ba9299d.png)

There are lots of connections with different ports and so i'm not entirely sure which ports I need to open

**Comment by Erikvv** [comment]
Unfortunately the storagenodes are not listening on a specific port, the default is 28967 but the node operator can host on any port.

**Comment by declanmarks** [comment]
I was able to get it working by opening all ports to nextcloud IP. 

It seems that it is using native mode. I was wondering if it is possible to use gateway mode, mainly because I don't have fast internet and so uploads take forever.

**Comment by Erikvv** [comment]
Select the S3 external storage instead of Storj.

You can get credentials with `uplink access register [accessgrant]`, or I think also through the sattelite web ui.
