### ISSUE TITLE
Support for Nextcloud 24

### ISSUE THREAD

**Issue by nunesgh** [storj-thirdparty/nextcloud-app#26]
Hi,

This app has currently no support for Nextcloud 24.

Is there a timeline for adding support for it?

Thank you for your attention.

**Comment by Tetricz** [comment]
Bumpin

**Comment by EdRoxter** [comment]
Bumpin 2.0

**Comment by WolfsWelpe** [comment]
Im currently using it under NExtcloud 24. It is working fine for me. So I guess it is supported?

**Comment by khinch** [comment]
> Im currently using it under NExtcloud 24. It is working fine for me. So I guess it is supported?

That's encouraging that it is working with 24. 

The page for the app shows it supports versions 20 through 23: https://apps.nextcloud.com/apps/storj

In version 24 it shows as available but untested: 
![image](https://user-images.githubusercontent.com/13088378/188263230-81d7f705-74a5-448b-ac39-d37cc5b90e60.png)

**Comment by WolfsWelpe** [comment]
> In version 24 it shows as available but untested: 

Yes sadly for me too. Under 24.0.3 it was tested, 24.0.4 made it an untested app :/

**Comment by pihomeserver** [comment]
I confirm that using the app in a build Nextcloud 24 with ffi php module works

Only one bug : creation of documents from templates does not work. You have to create it in the local storage and then move the doc into the external storage

**Comment by Erikvv** [comment]
Just done the release for 25

> Only one bug : creation of documents from templates does not work. You have to create it in the local storage and then move the doc into the external storage

I fixed this.
