### ISSUE TITLE
Question: Which Satellite is being used?

### ISSUE THREAD

**Issue by WolfsWelpe** [storj-thirdparty/nextcloud-app#29]
Hello,

im quite new to storj and didn't get all of it yet.
I successfully managed to set up Storj in nextcloud with my first bucket.
But I somewhere read that you have to choose a suitable Satelite? Is this app already using the best one
or do I have to set it somewhere?

**Comment by Erikvv** [comment]
You can pick when you sign up:

![Screenshot from 2022-08-08 07-44-50](https://user-images.githubusercontent.com/1748197/183347604-023d5894-c33f-46d7-9662-28986d4fbb1b.png)

**Comment by WolfsWelpe** [comment]
> You can pick when you sign up at [storj.io](https://storj.io)
> 
> ![Screenshot from 2022-08-08 07-44-50](https://user-images.githubusercontent.com/1748197/183347604-023d5894-c33f-46d7-9662-28986d4fbb1b.png)

Thank you!
