### ISSUE TITLE
Storj installed and configured but no file sync and displayed

### ISSUE THREAD

**Issue by pihomeserver** [storj-thirdparty/nextcloud-app#32]
I switched from a nextcloud running with docker (where Storj was running great) to a nextcloud instance managed by Yunohost
I can install and configure Storj, the green check is displayed in the parameter of the external storage
Unfortunatly the folder remains empty and does not display the files that are in the bucket and visible on the Storj website

I could not find any revelant information in logs (PHP or Nginx)

- Architecture is a x64 VPS running Debian 11
- Nextcloud version is 24.0.7
- PHP version is 8.0
- Using Storj as external storage only in a dedicated folder

**Comment by Erikvv** [comment]
This is usually caused by using two different encryption keys (=passphrases).

Can you copy over the access grant from the working instance to the new one? Or else make a new access grant with the same passphrase.

**Comment by pihomeserver** [comment]
A new access token with the same passphrase solved the issue

Thanks
