### ISSUE TITLE
unable to connect bucket to NC 

### ISSUE THREAD

**Issue by BSN-1312** [storj-thirdparty/nextcloud-app#33]
- Architecture: Ubuntu 22.04 ARM64 - Apache 2.4.54 - NGINX - HestiaCP 
- Nextcloud version: 25
- PHP version: 8.1
- Using Storj as external storage
- I've filled out the fields in the app to reflect bucket name and access.
So far i've tried access grant and later tried APi key after the access grant didn't connect.
Where should i begin trouble shooting?

![Screen Shot 2023-01-04 at 20 20 08](https://user-images.githubusercontent.com/83273891/210553872-5c8e815a-7fed-46eb-9fda-bde882e70485.png)

**Comment by Erikvv** [comment]
Hoover/click on the red "!" to view the error message.

**Comment by BSN-1312** [comment]
It was so obvious i over looked it!
Many thanks Erik.
