### ISSUE TITLE
Connection error, Failed loading libuplink-x86_64-linux.so

### ISSUE THREAD

**Issue by baldman30** [storj-thirdparty/nextcloud-app#34]
Hello,
I have manged to install the storj nextcloud app using DOCKER_MODS. Everything seems fine so far. I just can’t connect to storj. I input the access grant etc. but it won’t connect.

#I'm running the linuxsever/nextcloud docker with these Docker_ Mods Environment variables:
DOCKER_MODS=linuxserver/mods:universal-package-install
INSTALL_PACKAGES=libffi|php81-ffi

#php.ini has the following:
extension=ffi
ffi.enable=true

#This is the error in Nextcloud:
There was an error with message: Failed loading ‘/config/www/nextcloud/apps/storj/vendor/storj/uplink/build/libuplink-x86_64-linux.so’: Error relocating /config/www/nextcloud/apps/storj/vendor/storj/uplink/build/libuplink-x86_64-linux.so: seteuid: initial-exec TLS resolves to dynamic definition in /config/www/nextcloud/apps/storj/vendor/storj/uplink/build/libuplink-x86_64-linux.so

Thanks :)

**Comment by Erikvv** [comment]
linuxsever/nextcloud is an Alpine-based docker image. This doesn't work with Uplink. 

Tracked at https://github.com/storj/uplink-c/issues/6

**Comment by Erikvv** [comment]
duplicate #8
