### ISSUE TITLE
Stored objects in incompatible format.

### ISSUE THREAD

**Issue by fredcwells** [storj-thirdparty/nextcloud-app#5]
1) Cannot copy Storj objects outside or Storj directory to any other native Nextcloud folder.
2) Objects stored are incompatible with rclone, which is the defacto client for Storj.  
 - Rclone lists full Storj directory paths as single objects/files.  
 - Unable to copy / sync Storj objects from Nextcloud using rclone.

**Comment by Erikvv** [comment]
Fixed in 0.0.5
