### ISSUE TITLE
Nextcloud backup to Storj

### ISSUE THREAD

**Issue by Sembeth** [storj-thirdparty/nextcloud-app#9]
Hello,
I just wanted to notify that there will be a new "easy to use" backup app in Nextcloud 23. 

Source: https://nextcloud.com/blog/beta-of-peer-to-peer-nextcloud-backup-app-now-available-for-testing/

Since it is already possible to use Storj as "external storage". It would also be possible to use the external storage mount for the new backup app.

Beware that files are divided into 100 MB chunks by default. Source: https://github.com/nextcloud/backup. Currently there is an open issue https://github.com/storj-thirdparty/nextcloud-app/issues/4.

Perhaps it would be helpful to provide step-by-step documentation. Or maybe this information could be helpful for marketing, as I assume many Nextcloud installations do not have backups.

- Nextcloud version: 23
- Using Storj as primary or external storage: external storage

**Comment by Erikvv** [comment]
Thanks, when it's released I'll dedicate some text for it in the readme.

**Comment by Erikvv** [comment]
I tested it but it doesn't seem quite production-ready yet.

**Comment by Sembeth** [comment]
Hello @Erikvv,
I saw https://www.storj.io/blog/regain-control-and-securely-collaborate-with-nextcloud-and-storj today.

Thank you for your time and work on this. I really appreciate it.

Can you give me a hint as to why it doesn't feel quite ready for production yet?

**Comment by Erikvv** [comment]
It had some bugs at the time so that I couldn't finish the backup and restore process. But I know the author has been working to get them fixed. 

I should test it again some time, or hear from people that the feature is working for them.

**Comment by Erikvv** [comment]
> I think this is related to the instructions at https://apps.nextcloud.com/apps/storj - "The PHP installation should have the FFI extension loaded and enabled unconditionally in php.ini".
> 
> So, my question is if it's possible to load and enable the FFI extension and how can i do that? Using the CLI commands inside the VM? I am not a pro with CLI commands...

If your VM has a desktop environment, you can do it through that. 

I suppose you have a Debian VM? 

1. Create a file `/etc/php/8.1/apache2/conf.d/storj.ini` (replace 8.1 by whatever version is applicable, the folder should already exist)
2. Put this line in it:

```
ffi.enable=true
```

3. Restart the VM, it should work now.

> Or should i wait for a Storj app update?

No, this will probably always be necessary.

**Comment by 31bado** [comment]
Hi Erik.

Thanks for the suggestion. I'll try ir.

What about running sudo nano /etc/php XPTO/apache2/php.ini

And edit with ffi.enable=true?

Thanks.

**Comment by Erikvv** [comment]
You can edit the original php.ini, but this will mean it won't be updated by the package manager.

**Comment by 31bado** [comment]
Hi Erik.

I returno to this topic because when i tried:

Create a file /etc/php/8.1/apache2/conf.d/storj.ini (replace 8.1 by whatever version is applicable, the folder should already exist)

The return was "there is no such file or directory".

Maybe because I'm using Ubuntu and the command line is different?...

I tried something like sudo nano /var/www/nextcloud/config/storj.ini and i added ffi.enabled >= true

But I didn't have any success and I don't know if this is correct at all.

Can you help?

Thanks in advance.

Carlos

**Comment by 31bado** [comment]
In fact, I'm running Ubuntu in a VM from this guys:

https://www.hanssonit.se/nextcloud-vm/

**Comment by Erikvv** [comment]
I booted that vm and it's using apache+fpm. The folder is at 

```
/etc/php/8.1/fpm/conf.d/
```

**Comment by 31bado** [comment]
Thanks Eric. I'll try the configuration on this folder. Carlos

**Comment by Erikvv** [comment]
I think this feature works. Closing the issue.
